// <auto-generated />
using System;
using AQBlog.Domain;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AQBlog.Domain.Migrations
{
    [DbContext(typeof(AQContext))]
    partial class AQContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.9")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AQBlog.Model.BlogDetail", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CategoryId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Subject")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Tags")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Title")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("UrlSlug")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("Id");

                    b.ToTable("BlogDetail");
                });

            modelBuilder.Entity("AQBlog.Model.Category", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Icon")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("ParentId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Title")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UrlSlug")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.ToTable("Category");

                    b.HasData(
                        new
                        {
                            Id = "2238bc13-e988-485f-9bf6-206fb5020f21",
                            CreatedOn = new DateTime(2021, 8, 14, 16, 42, 38, 955, DateTimeKind.Utc).AddTicks(7640),
                            Description = "ASP.NET Frame work",
                            Icon = "",
                            IsDeleted = false,
                            ModifiedOn = new DateTime(2021, 8, 14, 16, 42, 38, 955, DateTimeKind.Utc).AddTicks(8864),
                            Title = "ASP.NET",
                            UrlSlug = "ASP-NET"
                        },
                        new
                        {
                            Id = "d2b2452b-734c-47f9-9828-a8894f004770",
                            CreatedOn = new DateTime(2021, 8, 14, 16, 42, 38, 956, DateTimeKind.Utc).AddTicks(699),
                            Description = "C# course",
                            Icon = "",
                            IsDeleted = false,
                            ModifiedOn = new DateTime(2021, 8, 14, 16, 42, 38, 956, DateTimeKind.Utc).AddTicks(703),
                            Title = "C#",
                            UrlSlug = "C-Sharp"
                        },
                        new
                        {
                            Id = "aeaa024d-8d86-4459-a1b7-25bd4f69465d",
                            CreatedOn = new DateTime(2021, 8, 14, 16, 42, 38, 956, DateTimeKind.Utc).AddTicks(708),
                            Description = "Sql Course",
                            Icon = "",
                            IsDeleted = false,
                            ModifiedOn = new DateTime(2021, 8, 14, 16, 42, 38, 956, DateTimeKind.Utc).AddTicks(710),
                            Title = "Sql",
                            UrlSlug = "Sql"
                        },
                        new
                        {
                            Id = "dacad5a6-1f4a-42dc-83f5-32ad05dd2fbf",
                            CreatedOn = new DateTime(2021, 8, 14, 16, 42, 38, 956, DateTimeKind.Utc).AddTicks(713),
                            Description = "Java script basic info",
                            Icon = "",
                            IsDeleted = false,
                            ModifiedOn = new DateTime(2021, 8, 14, 16, 42, 38, 956, DateTimeKind.Utc).AddTicks(714),
                            Title = "Java Script",
                            UrlSlug = "Java-Script"
                        },
                        new
                        {
                            Id = "178781c6-035a-43a6-b04f-73c85313e191",
                            CreatedOn = new DateTime(2021, 8, 14, 16, 42, 38, 956, DateTimeKind.Utc).AddTicks(725),
                            Description = "Angular Details",
                            Icon = "",
                            IsDeleted = false,
                            ModifiedOn = new DateTime(2021, 8, 14, 16, 42, 38, 956, DateTimeKind.Utc).AddTicks(726),
                            Title = "Angular",
                            UrlSlug = "Angular"
                        },
                        new
                        {
                            Id = "363a9d86-d8f8-43c5-bd0f-f46ee53e44d3",
                            CreatedOn = new DateTime(2021, 8, 14, 16, 42, 38, 956, DateTimeKind.Utc).AddTicks(729),
                            Description = "Mongodb Details",
                            Icon = "",
                            IsDeleted = false,
                            ModifiedOn = new DateTime(2021, 8, 14, 16, 42, 38, 956, DateTimeKind.Utc).AddTicks(730),
                            Title = "MongoDb",
                            UrlSlug = "MongoDb"
                        },
                        new
                        {
                            Id = "67c6687e-47fd-4711-a184-4abafed43d5d",
                            CreatedOn = new DateTime(2021, 8, 14, 16, 42, 38, 956, DateTimeKind.Utc).AddTicks(733),
                            Description = "ASP.Net Mvc Basic Detail",
                            Icon = "",
                            IsDeleted = false,
                            ModifiedOn = new DateTime(2021, 8, 14, 16, 42, 38, 956, DateTimeKind.Utc).AddTicks(734),
                            Title = "ASP.NET MVC",
                            UrlSlug = "ASP-NET-MVC"
                        },
                        new
                        {
                            Id = "0e2ba2e5-fb3e-4706-8973-89317fdea090",
                            CreatedOn = new DateTime(2021, 8, 14, 16, 42, 38, 956, DateTimeKind.Utc).AddTicks(737),
                            Description = "ASP.NET Core description",
                            Icon = "",
                            IsDeleted = false,
                            ModifiedOn = new DateTime(2021, 8, 14, 16, 42, 38, 956, DateTimeKind.Utc).AddTicks(738),
                            Title = "ASP.NET Core",
                            UrlSlug = "ASP-NET-CORE"
                        },
                        new
                        {
                            Id = "6ef0af10-810a-4d9c-aad7-b898b211cbab",
                            CreatedOn = new DateTime(2021, 8, 14, 16, 42, 38, 956, DateTimeKind.Utc).AddTicks(742),
                            Description = "ASP.NET Blazor Details",
                            Icon = "",
                            IsDeleted = false,
                            ModifiedOn = new DateTime(2021, 8, 14, 16, 42, 38, 956, DateTimeKind.Utc).AddTicks(742),
                            Title = "ASP.NET Blazor",
                            UrlSlug = "ASP-NET-BLAZOR"
                        });
                });

            modelBuilder.Entity("AQBlog.Model.Comment", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("BlogId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Comment");
                });

            modelBuilder.Entity("AQBlog.Model.MasterDetail", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("MasterCode")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("MasterContent")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("MasterDetail");

                    b.HasData(
                        new
                        {
                            Id = "e624c553-ff33-4ab3-922d-e01f02e86c23",
                            CreatedOn = new DateTime(2021, 8, 14, 16, 42, 38, 956, DateTimeKind.Utc).AddTicks(1797),
                            IsDeleted = false,
                            MasterCode = "TAGS",
                            MasterContent = "ASP.NET",
                            ModifiedOn = new DateTime(2021, 8, 14, 16, 42, 38, 956, DateTimeKind.Utc).AddTicks(2158)
                        },
                        new
                        {
                            Id = "2477d88a-7818-483f-8910-43114b28d4b7",
                            CreatedOn = new DateTime(2021, 8, 14, 16, 42, 38, 956, DateTimeKind.Utc).AddTicks(2169),
                            IsDeleted = false,
                            MasterCode = "TAGS",
                            MasterContent = "SQL",
                            ModifiedOn = new DateTime(2021, 8, 14, 16, 42, 38, 956, DateTimeKind.Utc).AddTicks(2170)
                        },
                        new
                        {
                            Id = "0e86582e-9bb2-4d2e-9ac1-8599d7360df9",
                            CreatedOn = new DateTime(2021, 8, 14, 16, 42, 38, 956, DateTimeKind.Utc).AddTicks(2174),
                            IsDeleted = false,
                            MasterCode = "TAGS",
                            MasterContent = "ASP.NET CORE",
                            ModifiedOn = new DateTime(2021, 8, 14, 16, 42, 38, 956, DateTimeKind.Utc).AddTicks(2175)
                        },
                        new
                        {
                            Id = "d6fae695-6ce1-4f30-a8d6-d142558b47ed",
                            CreatedOn = new DateTime(2021, 8, 14, 16, 42, 38, 956, DateTimeKind.Utc).AddTicks(2183),
                            IsDeleted = false,
                            MasterCode = "TAGS",
                            MasterContent = "SQL",
                            ModifiedOn = new DateTime(2021, 8, 14, 16, 42, 38, 956, DateTimeKind.Utc).AddTicks(2184)
                        },
                        new
                        {
                            Id = "8d5984d7-e206-4628-acd7-25f20f595bce",
                            CreatedOn = new DateTime(2021, 8, 14, 16, 42, 38, 956, DateTimeKind.Utc).AddTicks(2187),
                            IsDeleted = false,
                            MasterCode = "TAGS",
                            MasterContent = "JavaScript",
                            ModifiedOn = new DateTime(2021, 8, 14, 16, 42, 38, 956, DateTimeKind.Utc).AddTicks(2188)
                        },
                        new
                        {
                            Id = "56b7aa8f-538c-4e9f-ba17-363781fc5e37",
                            CreatedOn = new DateTime(2021, 8, 14, 16, 42, 38, 956, DateTimeKind.Utc).AddTicks(2191),
                            IsDeleted = false,
                            MasterCode = "TAGS",
                            MasterContent = "Angular",
                            ModifiedOn = new DateTime(2021, 8, 14, 16, 42, 38, 956, DateTimeKind.Utc).AddTicks(2192)
                        },
                        new
                        {
                            Id = "d732b556-0cab-4753-8b9a-87a1e74208b0",
                            CreatedOn = new DateTime(2021, 8, 14, 16, 42, 38, 956, DateTimeKind.Utc).AddTicks(2195),
                            IsDeleted = false,
                            MasterCode = "TAGS",
                            MasterContent = "MongoDb",
                            ModifiedOn = new DateTime(2021, 8, 14, 16, 42, 38, 956, DateTimeKind.Utc).AddTicks(2196)
                        },
                        new
                        {
                            Id = "479c057a-967a-4db3-b7c7-acd5f9bed53c",
                            CreatedOn = new DateTime(2021, 8, 14, 16, 42, 38, 956, DateTimeKind.Utc).AddTicks(2199),
                            IsDeleted = false,
                            MasterCode = "TAGS",
                            MasterContent = "ASP.NET Blazor",
                            ModifiedOn = new DateTime(2021, 8, 14, 16, 42, 38, 956, DateTimeKind.Utc).AddTicks(2200)
                        });
                });

            modelBuilder.Entity("AQBlog.Model.UserDetail", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Password")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SaltPassword")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("UserName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("UserDetail");

                    b.HasData(
                        new
                        {
                            Id = "032e39d9-fe32-46c5-aa7f-2bb70413240d",
                            IsDeleted = false,
                            Password = "Bqwq12Laz1VTk4HK95C99Q==",
                            SaltPassword = "e39b5a70d4f24f789ada1a5227a18720",
                            UserName = "sarfaraz.naushad@gmail.com"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
